constants:
  jackson:
    date-format: yyyy-MM-dd
    datetime-format: yyyy-MM-dd HH:mm:ss
  swagger:
    info:
      title: SpringJPA
      description: 여러가지 작업
      version: v0.1



spring:
  application:
    name: SpringJPA
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://localhost:3306/spring_jpa
    username: root
    password: green502
  jpa:
    database: mysql
    hibernate:
      #ddl-auto: create #entity를 서버 기동때마다 drop 후 create 한다.
      ddl-auto: update #entity가 없으면 create, 기존 존재하는 entity는 컬럼을 새롭게 추가하는 것만 반영
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        format_sql: true #로그 찍을 때 보기편하게 포맷팅
        order_updates: true #JPA Batch 작업 활성화

springdoc:
  swagger-ui:
    default-model-expand-depth: 10
    display-request-duration: true
    groups-order: asc
    operations-sorter: method
    path: /swagger
    tags-sorter: alpha
  cache:
    disabled: true